function Hd = bandpass3
%BANDPASS3 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.10 and Signal Processing Toolbox 8.6.
% Generated on: 26-May-2021 22:37:35

% Equiripple Bandpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 48000;  % Sampling Frequency

N      = 500;    % Order
Fstop1 = 11950;  % First Stopband Frequency
Fpass1 = 12973;  % First Passband Frequency
Fpass2 = 17027;  % Second Passband Frequency
Fstop2 = 18050;  % Second Stopband Frequency
Wstop1 = 40;     % First Stopband Weight
Wpass  = 10;     % Passband Weight
Wstop2 = 700;    % Second Stopband Weight
dens   = 20;     % Density Factor

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, [0 Fstop1 Fpass1 Fpass2 Fstop2 Fs/2]/(Fs/2), [0 0 1 1 0 ...
           0], [Wstop1 Wpass Wstop2], {dens});
Hd = dfilt.dffir(b);

% [EOF]
