function Hd = bandpass1
%BANDPASS1 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.10 and Signal Processing Toolbox 8.6.
% Generated on: 26-May-2021 23:48:37

% Equiripple Bandpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 48000;  % Sampling Frequency

N      = 500;   % Order
Fstop1 = 0.001;     % First Stopband Frequency
Fpass1 = 0.9;     % First Passband Frequency
Fpass2 = 6000;  % Second Passband Frequency
Fstop2 = 6000.001;  % Second Stopband Frequency
Wstop1 = 10;    % First Stopband Weight
Wpass  = 40;    % Passband Weight
Wstop2 = 800;   % Second Stopband Weight
dens   = 20;    % Density Factor

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, [0 Fstop1 Fpass1 Fpass2 Fstop2 Fs/2]/(Fs/2), [0 0 1 1 0 ...
           0], [Wstop1 Wpass Wstop2], {dens});
Hd = dfilt.dffir(b);

% [EOF]
